services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    security_opt:
      - no-new-privileges:true

  stable-diffusion:
      build:
          context: ./stable-diffusion-webui
          dockerfile: Dockerfile
      runtime: nvidia
      ports:
          - "7860:7860"
      volumes:
        - ./models:/app/stable-diffusion-webui/models
        - ./outputs:/app/stable-diffusion-webui/outputs
      environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      security_opt:
        - no-new-privileges:true
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]