services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    security_opt:
      - no-new-privileges:true

  stable-diffusion:
      build:
          context: ./stable-diffusion
          dockerfile: Dockerfile
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [ gpu ]
      ports:
          - "7860:7860"
      volumes:
        - ./stable-diffusion/models:/app/stable-diffusion-webui/models
        - ./stable-diffusion/outputs:/app/stable-diffusion-webui/outputs
      environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      security_opt:
        - no-new-privileges:true

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "11434:11434"
    security_opt:
        - no-new-privileges:true
    volumes:
      - ./ollama/models:/root/.ollama
