services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    security_opt:
      - no-new-privileges:true

  stable-diffusion:
      build:
          context: ./stable-diffusion
          dockerfile: Dockerfile
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [ gpu ]
      ports:
          - "7860:7860"
      volumes:
        - ./stable-diffusion/models:/app/stable-diffusion-webui/models
        - ./stable-diffusion/outputs:/app/stable-diffusion-webui/outputs
      environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      security_opt:
        - no-new-privileges:true


  deepseek-vllm:
    build:
      context: ./vllm
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "5000:5000"
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,utility
        - TENSOR_PARALLEL_SIZE=1
        - GPU_MEMORY_UTIL=0.95
        - MAX_TOKENS=4096
    security_opt:
        - no-new-privileges:true
    volumes:
      - ./vllm/deepseek-cache:/app/huggingface
    shm_size: "2gb"
    ulimits:
      memlock: -1
      stack: 67108864